language: ruby
env:
  - DB=mysql:utf8_general_ci
  - DB=mysql:utf8_bin
  - DB=pg DB_USER=postgres
  - DB=sqlite
gemfile:
  - Gemfile.rails3
  - Gemfile.rails4
rvm:
  - 1.8.7
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile.rails4
    - rvm: rbx-18mode
      gemfile: Gemfile.rails4
