language: ruby
env:
  - DB=mysql:utf8_general_ci
  - DB=mysql:utf8_bin
  - DB=pg DB_USER=postgres
  - DB=sqlite
gemfile:
#  - Gemfile.rails4
#  - Gemfile.rails41
#  - Gemfile.rails42
  - Gemfile.rails5
rvm:
#  - 2.1.2
  - 2.2.2
