sudo: false
language: ruby
addons:
  postgresql: "9.4"
env:
  - DB=mysql:utf8_general_ci
  - DB=mysql:utf8_bin
  - DB=pg DB_USER=postgres
  - DB=sqlite
gemfile:
  - Gemfile.rails4
  - Gemfile.rails41
  - Gemfile.rails42
rvm:
  - 2.1.0
  - 2.2.0
