sudo: false
language: ruby
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  - DB=mysql:utf8_general_ci
  - DB=mysql:utf8_bin
  - DB=pg DB_USER=postgres
  - DB=sqlite
gemfile:
  - Gemfile.rails5
  - Gemfile.rails51
rvm:
  - 2.4.3
  - 2.5.0
